CREATE TABLE IF NOT EXISTS rooms (
    room_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number     VARCHAR(20)  NOT NULL UNIQUE,
    room_type       VARCHAR(50)  NOT NULL,
    price_per_night DOUBLE       NOT NULL,
    capacity        INTEGER      NOT NULL,
    image_url       VARCHAR(500),
    status          VARCHAR(20)  NOT NULL DEFAULT 'Available'
);

CREATE TABLE IF NOT EXISTS guests (
    guest_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(120) NOT NULL,
    email       VARCHAR(120) NOT NULL UNIQUE,
    phone       VARCHAR(40)  NOT NULL,
    address     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id         INTEGER      NOT NULL,
    room_id          INTEGER      NOT NULL,
    check_in         DATE         NOT NULL,
    check_out        DATE         NOT NULL,
    actual_check_out DATE,
    number_of_guests INTEGER      NOT NULL,
    total_amount     DOUBLE       NOT NULL,
    status           VARCHAR(30)  NOT NULL DEFAULT 'Confirmed',
    CONSTRAINT fk_booking_guest FOREIGN KEY (guest_id) REFERENCES guests (guest_id),
    CONSTRAINT fk_booking_room  FOREIGN KEY (room_id)  REFERENCES rooms (room_id)
);
